#!/bin/bash

if [ $# -eq 0 ]; then
    echo "No arguments provided, building both"

    pyinstaller rna_app.py --onedir --clean --noconfirm --log-level WARN -w --distpath ./dist/dist_rna --workpath ./build/build_rna
    pyinstaller plot_app.py --onedir --clean --noconfirm --log-level WARN -w --distpath ./dist/dist_plot --workpath ./build/build_plot

    
fi

if [ "$1" = "rna" ]; then
    pyinstaller rna_app.py --onedir --clean --noconfirm --log-level WARN -w --distpath ./dist/dist_rna --workpath ./build/build_rna
fi

if [ "$1" = "plot" ]; then
    pyinstaller plot_app.py --onedir --clean --noconfirm --log-level WARN -w --distpath ./dist/dist_plot --workpath ./build/build_plot
fi