#!/bin/bash
./build
echo "Running app..."
if [ $# -eq 0 ]; then
    echo "No arguments provided."
    exit 1
fi

if [ "$1" = "rna" ]; then
    python app.py
fi

if [ "$1" = "plot" ]; then
    python plotter.py
fi


