#!/bin/bash
./build
echo "Running app..."
if [ $# -eq 0 ]; then
    echo "No arguments provided."
    exit 1
fi

if [ "$1" = "rna" ]; then
    python rna_app.py
fi

if [ "$1" = "plot" ]; then
    python plot_app.py
fi


